
CREATE DATABASE IF NOT EXISTS nova_vistaDB;

USE nova_vistaDB;

CREATE USER IF NOT EXISTS 'nova_vista'@'localhost' IDENTIFIED BY '';
ALTER USER 'nova_vista'@'localhost' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON nova_vistaDB.* TO 'nova_vista'@'localhost';

FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS event_bookings (
    id INT AUTO_INCREMENT PRIMARY KEY,
    eventDate DATE NOT NULL,
    eventType VARCHAR(255) NOT NULL,
    timeSlot VARCHAR(255) NOT NULL,
    budget VARCHAR(255) NOT NULL,
    decoration VARCHAR(255) NOT NULL,
    catering VARCHAR(255) NOT NULL,
    terms BOOLEAN NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SHOW TABLES;
SELECT * FROM event_bookings;